### ISSUE TITLE
Planck likelihood code not finding Cython

### ISSUE THREAD

**Issue by InterstellarDragon** [baudren/montepython_public#124]

**Comment by lesgourg** [comment]
This is not the right page nor the right version of the code! You found here a very old MontePython. As written on the front page and advertised in many places, MontePyhton has moved there since a couple of years:
https://github.com/brinckmann/montepython_public
There, you will be able to clone or download MontePyhton >= 3.2.0. If you have further problems, you can raise issues on that website.
