### ISSUE TITLE
plot tensor to scalar ratio vs spectral index

### ISSUE THREAD

**Issue by mohit93725** [baudren/montepython_public#127]
Dear all,
I am trying to use montepython3.0 to make contour plots between tensor to scalar ratio (r_T) vs spectral index (n_s). I am having a problem in assigning a value in .param file, and its plotting.
Any suggestions will be appreciated.
Thankyou

**Comment by lesgourg** [comment]
This is not the right page nor the right version of the code! You found here a very old MontePython. As written on the front page and advertised in many places, MontePyhton has moved there since a couple of years:
https://github.com/brinckmann/montepython_public
There, you will be able to clone or download MontePyhton >= 3.2.0. If you have further problems, you can raise issues on that website.
