### ISSUE TITLE
1D posterior could not be processed normally

### ISSUE THREAD

**Issue by ClaudioNahmad** [baudren/montepython_public#130]
Hello,

I am running MontePython with Planck2015 (TT+lowP) + JLA + BAO BOSS DR12 to probe a dark energy parameterization. After running successfully and trying to annalize the chains with the command:

`python montepython/MontePython.py info chains/N2_nakawe/bao_jla_planck/nkw_1-3_cluster1_f1.7/ --want-covmat`

I get the following error:

```
-> Computing histograms for  omega_b
 /!\ The 1D posterior could not be processed normally, probablydue to incomplete
     or obsolete numpy and/or scipy versions.So the raw histograms will be
     plotted.
```

Im running with a Python2.7 environment with all the packages that are expected, my numpy and scipy versions are:
- Numpy= 1.13.0-py27_0 
- Scipy = 0.19.1-np113py27_0

Is it a negligible error/warning? or is it changing the output of the histograms to be computed?

I've not had any problems while running Planck or any other likelihoods.
If anyone could lend a hand here, it'd be appreciated!
Thank you in advance,

- Claudio Nahmad

**Comment by lesgourg** [comment]
This is not the right page nor the right version of the code! You found here a very old MontePython. As written on the front page and advertised in many places, MontePyhton has moved there since a couple of years:
https://github.com/brinckmann/montepython_public
There, you will be able to clone or download MontePyhton >= 3.2.0. If you have further problems, you can raise issues on that website.
