### ISSUE TITLE
clik?

### ISSUE THREAD

**Issue by kangjg** [baudren/montepython_public#136]
Hi,  I meet a bug when run  montepython calling class:
"/home/kjg/montepython_public/montepython/likelihood_class.py", line 892, in __init__
    except clik.lkl.CError:
AttributeError: 'module' object has no attribute 'lkl'
how to solve the problem?
thank you!

**Comment by lesgourg** [comment]
Dear user, 
your are raising issues on the old MontePython repository (active in 2013-2018). As clearly stated on the wiki of this repository, since April 2018 and version 3.0, the MontePython repository  has moved to https://github.com/brinckmann/montepython_public
Please go there to clone recent, working and maintained versions of the code, and raise issues if necessary.
