### ISSUE TITLE
Class did not read input parameters : Omega_m

### ISSUE THREAD

**Issue by Truk8** [baudren/montepython_public#139]
Hi,
I follow this https://lesgourg.github.io/class-tour/Tokyo2014/jla.pdf in order to make the jla analysis, the first launch of MCMC chains works fine with :
mpiexec -n 1 -f machinefile python montepython/MontePython.py run -p input/jla.param -o chains/jla/ -N 1000
 but if I retry to launch the same chain with the same command I've got the error : Class did not read input parameters : Omega_m 

I don't understand what's going wrong?

Thank's for your help

**Comment by lesgourg** [comment]
Dear user, 
your are raising issues on the old MontePython repository (active in 2013-2018). As clearly stated on the wiki of this repository, since April 2018 and version 3.0, the MontePython repository  has moved to https://github.com/brinckmann/montepython_public
Please go there to clone recent, working and maintained versions of the code, and raise issues if necessary.
