### ISSUE TITLE
Getting dCl from CLASS

### ISSUE THREAD

**Issue by ShazAlvi** [baudren/montepython_public#140]
I am trying to get the density Cls from CLASS. I passed dCl in the parameter list along with tCl and pCl (as I was using them previously and now I want to add). I also wanted to save it in a file so I used this code in Python to get those Cls into an array:

Cl_tg_CLASS[:, :] = cl['td'][self.lmin:self.lmax+1]

When I run this, two funny things happen. 1) the flag, 'td' is not recognized but I believe this is the right flag for the said Cls. Secondly, my log.param file looks very weird,

![image](https://user-images.githubusercontent.com/63428526/78944695-c07cca00-7abe-11ea-9a75-deebea859915.png)

As soon as I remove the flag dCl, it does back to the normal statement which does not include the repetition of the flags. I am not sure what is wrong here? 

Thanks for your time.

**Comment by lesgourg** [comment]
Dear user, 
your are raising issues on the old MontePython repository (active in 2013-2018). As clearly stated on the wiki of this repository, since April 2018 and version 3.0, the MontePython repository  has moved to https://github.com/brinckmann/montepython_public
Please go there to clone recent, working and maintained versions of the code, and raise issues if necessary.
