### ISSUE TITLE
How to initialize SCF model in Montepython?

### ISSUE THREAD

**Issue by nkhadka21** [baudren/montepython_public#142]
Hi,
I am new at Montepython. I want to use Montepython to extract cosmological parameters using the SCF model. I tried to write a .param file for the SCF model but it gave me an error message which is given below.

Something went wrong when calling CLASS
/o\ Error in Class: input_init(L:455) :error in
input_read_parameters(&(fzw.fc), ppr, pba, pth, ppt, ptr, ppm, psp, pnl,
ple, pop, errmsg);
=>input_read_parameters(L:1396) :condition (pba->scf_tuning_index >=
pba->scf_parameters_size) is true; Tuning index scf_tuning_index = 0 is
larger than the number of entries 0 in scf_parameters. Check your .ini
file.

Could anyone suggest to me how to run the SCF model in Montepython? Any suggestions will be appreciated.

Thank you

Narayan

**Comment by lesgourg** [comment]
Your are raising issues on the old MontePython repository (active in 2013-2018). As clearly stated on the wiki of this repository, since April 2018 and version 3.0, the MontePython repository  has moved to https://github.com/brinckmann/montepython_public
Please go there to clone recent, working and maintained versions of the code, and raise issues if necessary.
