### ISSUE TITLE
Citations for dependencies

### ISSUE THREAD

**Issue by JohannesBuchner** [baudren/montepython_public#143]
Dear all,

The readme mentions "When using Monte Python in a publication, please acknowledge the code by citing the following paper. If you used Class, Nested Sampling or Cosmo Hammer, you should also cite the original works." 

Would it be possible to make it easier for users to link to the relevant citations?
For PyMultiNest, this would be http://arxiv.org/abs/arXiv:1402.0004 and Feroz & Hobson (2010).
I am asking because I have identified recent preprints which only cite MontePython and MultiNest.

As you know, developing software is an underappreciated activity in astronomy research. The only reward we can obtain are citations (which do not cost the writers anything). I h

Cheers,
             Johannes

**Comment by lesgourg** [comment]
Your are raising issues on the old MontePython repository (active in 2013-2018). As clearly stated on the wiki of this repository, since April 2018 and version 3.0, the MontePython repository  has moved to https://github.com/brinckmann/montepython_public
Please go there to clone recent, working and maintained versions of the code, and raise issues if necessary.
