### ISSUE TITLE
Is it compulsory to install Multinest? Montepython not working

### ISSUE THREAD

**Issue by annaefre** [baudren/montepython_public#39]
Hello,
I just installed montepython via
git clone https://github.com/baudren/montepython_public
cd montepython_public
python setup.py install --user

then I do   "python montepython/MontePython.py run --help"  and I obtain this

ERROR:   Could not load MultiNest library "libmultinest.so"
ERROR:   You have to build it first,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html

ERROR:   Could not load MultiNest library: libmultinest.so
ERROR:   You have to build MultiNest,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html

problem: libmultinest.so: cannot open shared object file: No such file or directory

Am I doing something wrong?
Thank you

**Comment by baudren** [comment]
Hello @annaefre 

No, the installation of Multinest is not mandatory. However, what you have probably done is installed `pymultinest`, without Multinest. You can check that it is the case by calling `pip list | grep pymultinest`.

If you have done this, Monte Python tries to import it, and fails, because Multinest is not installed below (`pymultinest` is just a thin wrapper around Multinest, and requires it to work).

You have two choices:
- `pip uninstall pymultinest`
- or follow the procedure on the [the pymultinest page]( http://johannesbuchner.github.com/PyMultiNest/install.html) to install everything properly (can be long).

**Comment by annaefre** [comment]
Thank you for your reply, now it is working!
