### ISSUE TITLE
sigma8

### ISSUE THREAD

**Issue by annaefre** [baudren/montepython_public#42]
Hello,
I am trying to insert sigma8 in the derived parameters. From what I can see in the classy.pyx and classy.pxd of the CLASS code version I am using (2.2.0), sigma8 seems to be a parameter that  Montepython recognizes. 
However when I put it in my param file

~~~ python
data.parameters['sigma8']    = [0.8,-1,-1, 0,     1,   'derived']
~~~

I obtain only zeros for sigma8.

Thanks in advance

**Comment by baudren** [comment]
Hello @annaefre ,

what are your other parameters in input? Did you set `mPk` in the desired output spectra? I think the default behaviour is to not compute `mPk`, and therefore `sigma8` is zero. Let me know

**Comment by annaefre** [comment]
Hello @baudren ,
I have checked my classy files and I have 
    def set_default(self):
        _pars = {
            "output":"tCl mPk",}
        self.set(**_pars)
Does not this mean I set mPk as output spectrum?
However I find in my log.param   
data.cosmo_arguments.update( 'output': ' tCl lCl pCl ')   
which means I do no have mPk aas output. Where should I set the output spectra?
Thank you in advance for your help

**Comment by baudren** [comment]
The output spectra are set automatically depending on which experiments you are testing. By selecting only CMB experiments, only Cls will be computed, to save time. The default behaviour you are seeing only affects `classy`, not the way MontePython calls `classy`.

To explicitely pass an argument to `classy`, you can use the following, in your `.param` file, after the `cosmological` and `derived` parameters:

~~~ python
...
data.cosmo_arguments['output'] = 'mPk'
...
~~~

It is the same way that what is used [in the base.param](https://github.com/baudren/montepython_public/blob/2.1/base.param#L69-L70) file.

Don't forget to remote your output folder first (the one containing the `log.param` you showed), otherwise re running will have no effect.

Let me know if things are solved,

**Comment by annaefre** [comment]
Now it works,
thank you for your help!
