### ISSUE TITLE
Montepython stops after a few hundreds steps & mpirun starts chains too fast

### ISSUE THREAD

**Issue by borisbolliet** [baudren/montepython_public#51]
When I run montepython on the cluster (cc-in2p3) with `mpirun`, the mcmc stops after afew hundreds steps (without any error message). The only way (thanks to @dirian) to bypass the problem seems to use the `-r` option, restarting the mcmc where it had stopped...

Did anyone stumble upon the same kind of issue?

Auxiliary question: Is there a way to use an environment variable in order to identify each process thrown by mpirun ? This is in order to use it as an argument to the option "`--chain-number`".

For instance with "`mpirun -np 8 [...]`" such variable "`$Process_ID`" would be an integer from 1 to 8 (or generally a set of 8 different integers). Then, with the option "`--chain-number $Process_ID`", the 8 different chains would be named "`blabla_$Process_ID.txt`"

Thank you

**Comment by ajcuesta** [comment]
Do you use the `--update` option in your runs?

I've seen sometimes my chains die one by one when I have a covmat that is not a good approximation of my problem. Eventually the job stops after all the chains are dead. I'm curious if you are using the` --update` option, because maybe the covmat generated automatically was not good enough. In that case I would increase the number in the `--update` option. Let me know if that works, I'm very interested!

Regarding your other question, I don't quite follow: if you run `mpirun -np 8` and don't use the option `--chain-number`, the chains will be appended an integer from 1 to 8, so you don't need to set an environment variable for that purpose.

**Comment by bellamayleonard** [comment]
Hello @ajcuesta ,

Merci beaucoup for your response/comments. Actually I was not aware of the --update option (I am a novice with montepython)!  So i am going to try this tomorrow and let you know as soon as I have found out.

For my other question, I am interested in doing this because I am using a shell script (kindly given to me by @dirian) that loops over the numbers of steps for a given chain, increasing it until it reaches the desired N:
```
for i in {1000..99000..1000}
do
    python montepython/MontePython.py -o ${chain}/ -p ${chain}.param -r ${chain}/*_${i}__1.txt --conf default.conf -f 0.5 --chain-number 1 -N 1000
    wait
done 
```
I would like to use it starting with mpirun -np $NSLOTS, however one needs to control the chain-number properly for the loop to make sense....

But if the --update option solves my problem, I won't need to use the loop anymore, anyway.

**Comment by borisbolliet** [comment]
(sorry I didn't pay attention: I was logged in onto my friend's account!)

**Comment by ajcuesta** [comment]
ah, I'm not familiar with doing restart with mpirun, but note that in your script you are clearly restarting _only_ the chain whose filename ends in "__1.txt" (even if you remove the `--chain-number` option)

I see also that you are not using the option `-c COV` . It should really help you with your problem if you start your chains with a covariance matrix adapted to your problem. For example, if your chains include Planck2015 CMB data, you can use the option `-c covmat/base2015.covmat` or `-c covmat/base2015TTTEEE.covmat` depending on which _Planck_highl_ likelihood is in your 'experiments' list in your parameter file.

**Comment by borisbolliet** [comment]
Dear @ajcuesta  and @dirian,

My problem was due to a wrong memory allocation, in a part of CLASS that I had modified (blame on myself).

Now, I can launch jobs without trouble. 

I also figured out thet the '-r' option is not suited to my needs, because it restart the chain from the last point, but there is a phase of burn-in each time the chain restarts. 

Therefore, doing:
`for i in {1000..99000..1000}
do
    python montepython/MontePython.py -o ${chain}/ -p ${chain}.param -r ${chain}/*_${i}__1.txt --conf default.conf -f 0.5 --chain-number 1 -N 1000
    wait
done 
`
is equivalent to start  100 chains, and not to start 1 chain with 100 000 steps.

Another thing I have learned is that mpirun starts the chains too fast. Generally, when the second chain starts, the log.param file is being read while it has not been written completely, then the job end with the error message "Information on the likelihood was not found in the log.param file".

To overcome this issue, one can copy the desired parameter file into the chain directory and rename it: log.param.

**Comment by mahtaparsa** [comment]
Dear Boris, 
I have the same problem, in which montepython stops after a few hundreds steps. However, I do not use cluster, and just using a single computer which is suitable for running MCMC. I did not come to this problem in previous runs. Everything was good and after three runs (the first one with 100000 steps, the second one with using bestfit and covmat of the previous run and with 200000 steps, and the third one with again using the previous bestfit and covmat with 300000 steps) I could analyze. However, recently I have problem with the third run which stop after a few hundreds steps. Is there any solution for this problem? I need the third run in order to constrain all parameters in model.
